export const ImagesAssets = {
    MenuIconsHeader: require('../../assets/alembicimages/dashboard/sideswipe.png'),
    SearchIconsHeader: require('../../assets/alembicimages/dashboard/searchwhite.png'),
    BellIconsHeader: require('../../assets/alembicimages/dashboard/nudge.png'),
    CardImages: require('../../assets/alembicimages/profile_user.jpg'),
    AgendaCardImages: require('../../assets/alembicimages/agendamap.gif'),
    AgendaCardImages2: require('../../assets/alembicimages/agenda.gif'),
    RunForTime: require('../../assets/alembicimages/dcr/runfortime.jpg'),
    Th: require('../../assets/alembicimages/dcr/th.jpg'),
    DCr_gif: require('../../assets/alembicimages/dcr/Dcr_gif.gif'),
    Tablets: require('../../assets/alembicimages/tablets.png'),
    Brandlogo: require('../../assets/alembicimages/logo.png'),
    BrandlogoTSPHARMA: require('../../assets/alembicimages/Wittrun.png'),
    Birthday: require('../../assets/alembicimages/birthday.gif'),
    BG: require('../../assets/alembicimages/background-pattern.png'),
    BGVIDEO: require('../../assets/alembicimages/wave-pattern.mp4'),
    Book: require('../../assets/alembicimages/dcr/book.png'),
    Form_img: require('../../assets/alembicimages/dcr/form_image.jpeg'),
    Doctor: require('../../assets/alembicimages/doctor.png'),
    Store: require('../../assets/alembicimages/store.png'),
    OTPGif: require('../../assets/alembicimages/OTPModalVideo/otpvideo.mp4'),
    Calandergif: require('../../assets/alembicimages/gif/calander.gif'),
    DCR: require('../../assets/alembicimages/doctor360/DCR.png'),
    AGGRI:require('../../assets/alembicimages/aggri_1.png'),
    Doctors: require('../../assets/alembicimages/default_doctor.png'),
    Cake: require('../../assets/alembicimages/birthday.gif'),
    Ring: require('../../assets/alembicimages/ring.png'),
    QuestionMark: require('../../assets/alembicimages/QuestionMark.gif'),
    WarningGif: require('../../assets/alembicimages/warningG.gif'),
    Home: require('../../assets/alembicimages/home.gif'),
    Stores: require('../../assets/alembicimages/stores.png'),
    DoctorImages: require('../../assets/alembicimages/doctorvector.png'),
    Survey: require('../../assets/alembicimages/survey.png'),
    Loading: require('../../assets/alembicimages/loading.gif'),
    // bannerList2: require('./gold.png'),
    // bannerList3: require('./dimound.png'),
    // bannerList4: require('./busniss.png'),
    ///you can add more many images like this here.
    WarningAlert: require('../../assets/alembicimages/gif/warning_alert.gif'),
    //---- survey ------
    VeryGood: require('../../assets/alembicimages/survey/VeryGood.png'),
    Good: require('../../assets/alembicimages/survey/Good.png'),
    Ok: require('../../assets/alembicimages/survey/Ok.png'),
    Bad: require('../../assets/alembicimages/survey/Bad.png'),
    VeryBad: require('../../assets/alembicimages/survey/VeryBad.png'),

    // NETCO
    medicine: require('../../assets/alembicimages/medicine.png'),
    areusure: require('../../assets/alembicimages/expesne/areusure.png'),
    noimagenew: require('../../assets/alembicimages/noimagenew.png'),
};